# Generated by Django 5.0.1 on 2024-02-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine2', models.CharField(max_length=50)),
                ('usage', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='doctereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedic.login1')),
            ],
        ),
        migrations.CreateModel(
            name='patientsreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedic.login1')),
            ],
        ),
        migrations.CreateModel(
            name='sendcomplaints1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=20)),
                ('reply', models.CharField(max_length=500)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedic.patientsreg')),
            ],
        ),
        migrations.CreateModel(
            name='shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('fromtime', models.TimeField()),
                ('totime', models.TimeField()),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedic.doctereg')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedic.patientsreg')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedic.shedule')),
            ],
        ),
        migrations.CreateModel(
            name='stafftreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedic.login1')),
            ],
        ),
    ]
